name:Testing
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.13'
            - run: pip install -U pip
            - run: pip install fastapi uvicorn[standard] asteval pytest httpx
            - run: pytest -q